## Name: Yeabsira Driba
## ID: UGR/4951/12

In [1]:
import torch

## Layers

In [2]:
class DenseLayer:
  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
    # Initialize weights and biases
    self.weights = 0.01 * torch.rand(n_inputs, n_neurons)
    self.biases = torch.zeros((1, n_neurons))

  # Forward pass
  def forward(self, inputs):
    # Calculate output values from inputs, weights and biases
    self.output = torch.matmul(inputs, self.weights) + self.biases

## Activation Functions

### ReLU

In [3]:
class Activation_ReLU:
  # Forward pass
  def forward(self, inputs):
    self.output = torch.max(torch.tensor(0),inputs)

### Sigmoid

In [4]:
class Activation_Sigmoid:
  # Forward pass
  def forward(self, inputs):
    self.output = 1 / (1 + torch.exp(inputs*-1))

## Loss

### Mean Squared Error

In [5]:
class Loss_MeanSquareError():
    # Forward pass
    def forward(self, y_pred, y_true):
        # Calculate the mean square error
        mse_loss = torch.mean((y_pred - y_true)**2)
        return mse_loss

## Accurace

In [6]:
class Accuracy():
  def calculate(self, y_pred, y_true):
    predictions = torch.argmax(y_pred, axis=1)
    if len(y_true.shape) == 2:
      y_true = torch.argmax(y_true, axis=1)
    accuracy = torch.mean((predictions == y_true).float())
    return accuracy

## Forward

In [7]:
X = torch.tensor([0.21, 0.66])
Y = torch.tensor([0.7, 0.3])

In [8]:
dense1 = DenseLayer(2, 2)
activation1 = Activation_ReLU()
output1 = DenseLayer(2, 2)
activation2 = Activation_Sigmoid()

In [9]:
dense1.forward(X)
activation1.forward(dense1.output)
output1.forward(activation1.output)
activation2.forward(output1.output)
activation2.output

tensor([[0.5000, 0.5000]])

### Back Prograpagation

In [10]:
def back_prop_two_neuron(fp):
  lr = torch.tensor(0.01)
  back1 = (fp[0][0]-Y[0])*(1-fp[0][0])*fp[0][0]
  back2 = (fp[0][1]-Y[1])*(1-fp[0][1])*fp[0][1]
  output1.weights[0][0] -= lr * back1*activation1.output[0][0]
  output1.weights[0][1] -= lr * back1*activation1.output[0][1]
  output1.weights[1][0] -= lr * back2*activation1.output[0][0]
  output1.weights[1][1] -= lr * back2*activation1.output[0][1]
  output1.biases[0][0] -= lr * back1
  output1.biases[0][1] -= lr * back2

  dense1.weights[0][0] -= lr * (back1 * output1.weights[0][0] * X[0] + back2 * output1.weights[0][1] * X[0] ) if dense1.output[0][0] > 0 else 0
  dense1.weights[0][1] -= lr * (back1 * output1.weights[0][0] * X[1] + back2 * output1.weights[0][1] * X[1] ) if dense1.output[0][0] > 0 else 0
  dense1.weights[1][0] -= lr * (back1 * output1.weights[1][0] * X[0] + back2 * output1.weights[1][1] * X[0] ) if dense1.output[0][1] > 0 else 0
  dense1.weights[1][1] -= lr * (back1 * output1.weights[1][0] * X[1] + back2 * output1.weights[1][1] * X[1] ) if dense1.output[0][1] > 0 else 0
  dense1.biases[0][0] -= lr * (back1 * output1.weights[0][0] + back2 * output1.weights[0][1] ) if dense1.output[0][0] > 0 else 0
  dense1.biases[0][1] -= lr * (back1 * output1.weights[1][0] + back2 * output1.weights[1][1] ) if dense1.output[0][1] > 0 else 0

In [11]:
print("===============================================")
print("NEW UPDATED WEIGHTS")
print("===============================================\n")

back_prop_two_neuron(activation2.output)
print("LAYER 1 NEW WEIGHTS:\n",dense1.weights)
print("\nLAYER 1 NEW BIAS: \n", dense1.biases)
print("\nOUTPUT LAYER NEW WEIGHT: \n", output1.weights)
print("\nOUPUT LAYER NEW BIAS: \n",output1.biases)


NEW UPDATED WEIGHTS

LAYER 1 NEW WEIGHTS:
 tensor([[0.0080, 0.0021],
        [0.0038, 0.0021]])

LAYER 1 NEW BIAS: 
 tensor([[-7.6248e-07,  1.2469e-06]])

OUTPUT LAYER NEW WEIGHT: 
 tensor([[0.0008, 0.0023],
        [0.0055, 0.0030]])

OUPUT LAYER NEW BIAS: 
 tensor([[ 0.0005, -0.0005]])
